language: node_js
node_js: lts/*
sudo: false
branches:
  only:
    - master
    - /^v\d+(\.\d+)+$/
cache:
  directories:
  - electron
  - node_modules
script:
- yarn run dist-all
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-wine/ppa'
    packages:
    - rpm
    - wine1.8
before_install:
  - ln /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
deploy:
  provider: releases
  api_key:
    secure: D5zYaGxt+XxxKcD+PIkZws7K0JNxR4IOIPWn7mMVx7+ebaKV0utwhjRZG8reNdVX6/zusj78SdPlYfO0olnWL78MFZ+Ac1K0LxTvcXcXmnGlpVRF/7CvlkzV0TItITYf4vIBUuQLiG+rid8EuO5ufW0uZRbw4teHvUc+fZQCJIUY7T/TkGlkjuTLlZyHFBVFYGXU4WAkfbPNSHk7Zzou9P4NYTHm8O70/D71g9b7RhuIGnnASe2pHNbkDBt+77bjv6BMD739kepwWSIBlwxwFgX7dyhFNOY9KkH/bH8t40xEmBJzAJaVxtmYvW+p3YxPbfpsYlSighQXPz/zN9o9qsARL0ZYIsYDJ/ltjuEf7LCt5CNzBFeEs6WhZJPD5H2duDp/nf6DFEJwvwJaBOnwBKeuia56UQ9NOa1iyFdw/O+OJzoqKTiLfkNSmn1v0Rz+09RtMpkffZnH9QEEU9dGdoIGKWjxwqOgB07kfiFdGGHKw3z577mvR2YmzQZQo+p1RUorlS+wJTWU4R8yJ71ehDxID67Ag9PNi64VQ3kl1tf5gJPteDBTFRCkKBR69KMTdHZzdLGd6Nlc/xxFjMlFY8sR8V01pGR+t9avFhdwXsuJP7JXhVRTbTNLN5mfSqeDFlX3ICBTsxmXhnMOmRHCidQulb5bXgba1wYbNDaF7Pk=
  file:
    - dist/openworldfactory*
    - latest.yml
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
